### ISSUE TITLE
Infininty Loop in the GameCountdown Class

### ISSUE THREAD

**Issue by Moglie42** [Janhektor/Community#37]
Hey everyone,
I wanted you to point out that there is a infinity loop in the GameCountdown class in the method start. For everyone who now wonders why there is a infinity loop is welcome to read the evidence at the ending of this comment. If I'm wrong then I'm sorry
sincerely
Moglie

evidence:
condition:
Given is the code of the method start from the GameCountdown class.

assertion: 
start method doesn't work

proof by contradiction:
Adopted the start method work. We set countdown onto 30, then follow with the modulo operation that we have to execute the first if block. Afterwards the program run until the countdown is less or equal 10. It follow that we have to execute the first if block until countdown is equal zero. With the modulo operation follow that we have to execute the first if block again. After execute the first if block the countdown have now a value of -1. With the condition of the first if we now execute the first if block in a infinity loop what brings the contradiction to the assertion.

**Comment by Blueses** [comment]
Also ich sehe hier im Moment keinen Fehler da in der letzten if Abfrage steht ob der countdown< 0 ist und wenn dem so wäre stoppt er ihn! MfG

**Comment by Moglie42** [comment]
Blueses, die unter if-abfragen werden ausgeführt wenn die erste If-Abfrage false ergibt und das ist in allen Fällen wo Countdown modulo 30 ungleich 0 und größer 10 ist, dies wiederum bringt ein Wert für Countdown der größer 10 ist. Damit folgt das die Bedingungen der unter if-abfragen immer false wirft. Sobald Countdown kleiner 10 wird nur noch die erste if abfrage durchgeführt. Würde man die else weg lassen, sodass immer alle if-abfragen ausgeführt werden, dann würde es einwandfrei laufen, eo bei man es auch kürzer schreiben kann. 
MfG

**Comment by TheRealJasmin** [comment]
Dont understand your language...

**Comment by Moglie42** [comment]
Hey Jasmin, you have right the main language of this project is english and not german, my fault. I will change my comments into the right language, that will take a few moments. For upcomming comments i will use for now on the right language.

**Comment by Janhektor** [comment]
We fixed this bug with an improved countdown API.
