### ISSUE TITLE
Missing proper code style.

### ISSUE THREAD

**Issue by Janmm14** [Janhektor/Community#46]
You allow different code styles in your project. This is not a good idea as it can lead to various unneeded diffs with git.

Additionally I strongly suggest using maven

**Comment by Rincewind34** [comment]
Janhektor said, that we will not use maven in his tutorials. And maybe you could tell us some examples for the diffrent codestyles?

**Comment by Janmm14** [comment]
1) Tabs or Spaces as identiation
2) Spaces in method calls or not (ex: ```someMethod( 1 )``` vs. ```someMethod(1)```
3) I got the information from the README file that multiple code styles are allowed.

**Comment by Janhektor** [comment]
You're right.
It's not a good idea, but there are multiply options to style your source code in these project.
Currently, I'm talking with some developers about this problem: In some cases we don't have decided for a rule yet. But I except we'll got finish in the next three weeks.
Now, I recommend to use the following guidelines for your examples:
1. Indention: Tabs (length must be comparable with four white spaces)
2. Spaces in method calls: Forbidden. Please don't use spaces in this case.

Now to Maven.
Maven is a comfortable and useful tool for build automation. It allows to configure and/or extend the build process - a good idea. There is only one reason against Maven: My tutorials about these project are simple. For advanced users it's okay - but I've many viewers they don't now what a BuildTool is - Maven would be too complicated. Sorry, but it's truth.

Thanks for reading,
Janhektor

**Comment by Janmm14** [comment]
I agree about maven

**Comment by Janhektor** [comment]
Yes, but see above.
If there are plenty of agreements, maybe I'll manage to use maven. But not yet.
